name: Deploy to CloudBase Static Hosting

on:
  push:
    branches:
      - main # 或 master，根据您的主分支名称

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to CloudBase Static Hosting
      env:
        # TCB_SECRET_ID和TCB_SECRET_KEY会自动被CLI识别
        TCB_SECRET_ID: ${{ secrets.TCB_SECRET_ID }}
        TCB_SECRET_KEY: ${{ secrets.TCB_SECRET_KEY }}
      run: |
        echo "$TCB_SECRET_ID" 
